### ISSUE TITLE
模型使用 - 如何对训练好的模型进行预测结果呢？

### ISSUE THREAD

**Issue by dhwgithub** [AaronJny/DeepLearningExamples#10]
例如输入一句评论，加载训练好的模型来输出对应的标签值

**Comment by AaronJny** [comment]
你是说tf2的微博情感分析那个demo吗？可以参考keras版本那个，有调用的示例。https://github.com/AaronJny/DeepLearningExamples/blob/master/keras-bert-emotional-classifier/eval.py
