### ISSUE TITLE
图片风格迁移评估指标

### ISSUE THREAD

**Issue by laikaiting** [AaronJny/DeepLearningExamples#13]
您好~我想问一下图片风格迁移的demo有没有什么可以作为评估指标的呢，还是只有两个loss和肉眼观察吗hhh

**Comment by AaronJny** [comment]
> 对于神经风格迁移问题，并不存在什么 ground truth。神经风格迁移是一种艺术创作。不同的人可能会对同一个迁移后的结果有不同乃至截然相反的看法。因此，对神经风格迁移算法所得到的视觉结果的评估仍然还是一个悬而未决的重要问题。

——摘自 https://github.com/OUCMachineLearning/OUCML/blob/master/%E4%BB%A3%E7%A0%81%E6%8A%80%E5%B7%A7%E6%B1%87%E6%80%BB/%E9%A3%8E%E6%A0%BC%E8%BF%81%E7%A7%BB%E6%B1%87%E6%80%BB.md

loss也只是我用来监控训练是否有效的工具，肉眼观察是唯一衡量指标2333~毕竟这个任务主观性太强了。

但也不是没有方法，上面的链接中有提供思路，感兴趣的话可以看一下~
