### ISSUE TITLE
你好，我在你的lstm生成古诗的模型中，出现了很多下面的警告你能帮我看看吗

### ISSUE THREAD

**Issue by jollazzlw** [AaronJny/DeepLearningExamples#2]
WARNING:tensorflow:11 out of the last 11 calls to <function _make_execution_function.<locals>.distributed_function at 0x000002A1DC21A400> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/beta/tutorials/eager/tf_function#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.

**Comment by AaronJny** [comment]
这是tensorflow的bug，目前还没有修复，相关信息你可以去tensorflow的github看一下。不过放心，这些警告并不影响程序执行。

**Comment by jollazzlw** [comment]
🆗 thanks

**Comment by jollazzlw** [comment]
> 这是tensorflow的bug，目前还没有修复，相关信息你可以去tensorflow的github看一下。不过放心，这些警告并不影响程序执行。

谢谢了，我在运行你bert生成古诗的模型时，生成的古诗的一句话总是有很多一样的词，是我哪里没有配置好吗
例如，这样
九衢晴兄画漫开。栋便柴耀卑杏梁尘。蕊嫁柴误转堪泛泛姬宣樱樱。手持岷宠孙羞间弄髦髦缓缓，柴虔掌凡斜虔耀。翻柴撩银髦曲，转绕画劝瑚
床前明月光，灵体秀郎幕。孔器初迎孙让，滟各昔滴香啾剖鸭翡英堕邛邛，氏武髻嫦酬酬片，褐蹉增韵迹弹。卷七八十斋种种勿熟，柯氛霰储氛
海眼旗恃翼，阔披畅妇喘。天歇鸥频末，空庭鸡巷语。
天号团顾杖鸦枉移。道招真祖线疏经，酬啼市踪踪稀。勤岛叹岳邹险

**Comment by AaronJny** [comment]
> > 这是tensorflow的bug，目前还没有修复，相关信息你可以去tensorflow的github看一下。不过放心，这些警告并不影响程序执行。
> 
> 谢谢了，我在运行你bert生成古诗的模型时，生成的古诗的一句话总是有很多一样的词，是我哪里没有配置好吗
> 例如，这样
> 九衢晴兄画漫开。栋便柴耀卑杏梁尘。蕊嫁柴误转堪泛泛姬宣樱樱。手持岷宠孙羞间弄髦髦缓缓，柴虔掌凡斜虔耀。翻柴撩银髦曲，转绕画劝瑚
> 床前明月光，灵体秀郎幕。孔器初迎孙让，滟各昔滴香啾剖鸭翡英堕邛邛，氏武髻嫦酬酬片，褐蹉增韵迹弹。卷七八十斋种种勿熟，柯氛霰储氛
> 海眼旗恃翼，阔披畅妇喘。天歇鸥频末，空庭鸡巷语。
> 天号团顾杖鸦枉移。道招真祖线疏经，酬啼市踪踪稀。勤岛叹岳邹险

你训练了多少epoch?应该是训练不足吧，基本的格式都没有学习到。

**Comment by jollazzlw** [comment]
> > > 这是tensorflow的bug，目前还没有修复，相关信息你可以去tensorflow的github看一下。不过放心，这些警告并不影响程序执行。
> > 
> > 
> > 谢谢了，我在运行你bert生成古诗的模型时，生成的古诗的一句话总是有很多一样的词，是我哪里没有配置好吗
> > 例如，这样
> > 九衢晴兄画漫开。栋便柴耀卑杏梁尘。蕊嫁柴误转堪泛泛姬宣樱樱。手持岷宠孙羞间弄髦髦缓缓，柴虔掌凡斜虔耀。翻柴撩银髦曲，转绕画劝瑚
> > 床前明月光，灵体秀郎幕。孔器初迎孙让，滟各昔滴香啾剖鸭翡英堕邛邛，氏武髻嫦酬酬片，褐蹉增韵迹弹。卷七八十斋种种勿熟，柯氛霰储氛
> > 海眼旗恃翼，阔披畅妇喘。天歇鸥频末，空庭鸡巷语。
> > 天号团顾杖鸦枉移。道招真祖线疏经，酬啼市踪踪稀。勤岛叹岳邹险
> 
> 你训练了多少epoch?应该是训练不足吧，基本的格式都没有学习到。

好像是的，权重保存的那个文件，有个问号 你知道什么原因吗

**Comment by AaronJny** [comment]
> > > > 这是tensorflow的bug，目前还没有修复，相关信息你可以去tensorflow的github看一下。不过放心，这些警告并不影响程序执行。
> > > 
> > > 
> > > 谢谢了，我在运行你bert生成古诗的模型时，生成的古诗的一句话总是有很多一样的词，是我哪里没有配置好吗
> > > 例如，这样
> > > 九衢晴兄画漫开。栋便柴耀卑杏梁尘。蕊嫁柴误转堪泛泛姬宣樱樱。手持岷宠孙羞间弄髦髦缓缓，柴虔掌凡斜虔耀。翻柴撩银髦曲，转绕画劝瑚
> > > 床前明月光，灵体秀郎幕。孔器初迎孙让，滟各昔滴香啾剖鸭翡英堕邛邛，氏武髻嫦酬酬片，褐蹉增韵迹弹。卷七八十斋种种勿熟，柯氛霰储氛
> > > 海眼旗恃翼，阔披畅妇喘。天歇鸥频末，空庭鸡巷语。
> > > 天号团顾杖鸦枉移。道招真祖线疏经，酬啼市踪踪稀。勤岛叹岳邹险
> > 
> > 
> > 你训练了多少epoch?应该是训练不足吧，基本的格式都没有学习到。
> 
> 好像是的，权重保存的那个文件，有个问号 你知道什么原因吗

请带上具体的问题信息，不然我没法确认你的问题。我不太清楚你表述的是什么意思，我这边一切正常。
