### ISSUE TITLE
tf2-rnn-poetry-generator h5模型转换为pb文件 相关

### ISSUE THREAD

**Issue by wjch** [AaronJny/DeepLearningExamples#5]
您好,我在在JAVA或者js中使用您的诗词训练代码中生成的模型 来完成我的毕业设计,但是使用网上通用的转换方案 转换过程中都会报 ValueError: Unknown layer: UnifiedLSTM,这个错误,我搜索了很长时间都没有对应的解答,请问您是否知道这个错误是什么意思呢

**Comment by AaronJny** [comment]
> 您好,我在在JAVA或者js中使用您的诗词训练代码中生成的模型 来完成我的毕业设计,但是使用网上通用的转换方案 转换过程中都会报 ValueError: Unknown layer: UnifiedLSTM,这个错误,我搜索了很长时间都没有对应的解答,请问您是否知道这个错误是什么意思呢

不好意思，没做过这方面的尝试，不太清楚该怎么解决，抱歉帮不到你了。如果你自行解决了，可以在此issue内补充，并关闭此issue。

**Comment by wjch** [comment]
谢谢,已经通过将服务转化为flask api,然后使用java远程调用api来间接实现了功能.

**Comment by AaronJny** [comment]
> 谢谢,已经通过将服务转化为flask api,然后使用java远程调用api来间接实现了功能.

好的，如果打算以api的形式提供服务的话，使用TensorFlow Serving可能会更加合适。可以参考https://tf.wiki/zh/deployment/serving.html
