### ISSUE TITLE
tf2-neural-style-transfer 的模型下载好了放那个路径呢

### ISSUE THREAD

**Issue by albertyou2** [AaronJny/DeepLearningExamples#7]
这个项目的模型我用迅雷下好的，放在跟目录
但是他每次启动还是要去download 这个要放哪个路径呢？谢谢
@AaronJny

**Comment by AaronJny** [comment]
tensorflow会自动下载并缓存模型，一般不需要手动下载。如果因为网络原因，必须手动下载的话，一般存放路径是`~/.keras/models`。
